apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: i-go-go-ns
      protocol: layer2
      addresses:
      - 192.168.64.2-192.168.64.22