apiVersion: v1
kind: Service
metadata:
  name: i-go-go-service
  namespace: i-go-go-ns
  labels:
    app: i-go-go
spec:
  type: LoadBalancer
  selector:
    app: i-go-go
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
