apiVersion: apps/v1
kind: Deployment
metadata:
  name: i-go-go-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: i-go-go
  template:
    metadata:
      labels:
        app: i-go-go
    spec:
      containers:
      - name: i-go-go
        image: igordubinin/i-go-go:1.0
        ports:
        - containerPort: 3000