version: "3.8"
services:
  i-go-go:
    build: .
    image: igordubinin/i-go-go:1.3
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: "mongodb-standalone-0.database"
      # MONGO_HOST: "192.168.99.100"
      # MONGO_PORT: "30017"
      MONGO_USER: "admin"
      MONGO_PASSWORD: "password"
      MONGO_AUTH: "true"