apiVersion: v1
kind: Secret
metadata:
  name: i-go-go-secrets
  namespace: i-go-go-ns
type: Opaque
data:
  MONGO_DB: ZGVsaXZlcnk=
  # MONGO_HOST: MTkyLjE2OC4xLjE5NQ==
  MONGO_HOST: bW9uZ29kYi0wLm1vbmdvZGItaGVhZGxlc3MuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNyxtb25nb2RiLTEubW9uZ29kYi1oZWFkbGVzcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
  MONGO_USER: ZGFkbWlu
  MONGO_PASSWORD: ZHBhc3N3b3Jk
  MONGO_REPLICASET: cnMw
  MONGO_AUTH: dHJ1ZQ==