name: Docker Image CI

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        id: build
        uses: docker/build-action@v1
        with:
          repository: igordubinin/i-go-go
          tag: v0.0.1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: igordubinin
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push image
        uses: docker/push-action@v1
        with:
          registry: igordubinin
          tags: ${{ outputs.build.tags }}